{% set name = "cachier" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cachier-{{ version }}.tar.gz
  sha256: 0a018f7474abd998c75382454e9d28c81f8ad32d66787eecedfd3d9791f523a2

build:
  entry_points:
    - cachier=cachier.__main__:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=67.6.0
  run:
    - portalocker >=2.3.2
    - python >={{ python_min }}
    - watchdog >=2.3.1

    # Not listed as required (it's optional) upstream but needed for import
    - click
    - pymongo

test:
  imports:
    - cachier
  commands:
    - pip check
    - cachier --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/shaypal5/cachier
  summary: Persistent, stale-free, local and cross-machine caching for Python functions.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
