{% set name = "cachier" %}
{% set version = "3.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cachier-{{ version }}.tar.gz
  sha256: 8ef53b6ae83ba04d8864d2e1f45eb8b46eecb611d0f6a24c006e8fda074c6557

build:
  entry_points:
    - cachier=cachier.__main__:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=67.6.0
  run:
    - portalocker >=2.3.2
    - python >=3.8
    - watchdog >=2.3.1

    # Not listed as required (it's optional) upstream but needed for import
    - click
    - pymongo

test:
  imports:
    - cachier
  commands:
    - pip check
    - cachier --help
  requires:
    - pip

about:
  home: https://github.com/shaypal5/cachier
  summary: Persistent, stale-free, local and cross-machine caching for Python functions.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
