{% set name = "cachier" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cachier-{{ version }}.tar.gz
  sha256: 32e61733bf25f9e082bd2a0d208946d99587297ff07d65fd10e54371ec7d7ca4
  patches:
    - 0001-add-scripts-package.patch

build:
  entry_points:
    - cachier=cachier.scripts.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click
    - pathtools
    - portalocker
    - python >=3.7
    - watchdog

test:
  imports:
    - cachier
  commands:
    - pip check
    - cachier --help
  requires:
    - pip

about:
  home: https://github.com/shaypal5/cachier
  summary: Persistent, stale-free, local and cross-machine caching for Python functions.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
