{% set name = "cachier" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cachier-{{ version }}.tar.gz
  sha256: a48fc2a03286a102d989280166336e54f1654d09f94be34a7e77463fa08d8e28

build:
  entry_points:
    - cachier=cachier.scripts.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=67.6.0
  run:
    - click
    - pathtools
    - portalocker
    - python >=3.8
    - watchdog

    # Not listed as required (it's optional) upstream but needed for import
    - pymongo

test:
  imports:
    - cachier
  commands:
    - pip check
    - cachier --help
  requires:
    - pip

about:
  home: https://github.com/shaypal5/cachier
  summary: Persistent, stale-free, local and cross-machine caching for Python functions.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
